### ISSUE TITLE
Add Poetry for dependencies management to give the choice to the users

### ISSUE THREAD

**Issue by groovytron** [groovytron/python-container#2]
https://python-poetry.org/

**Comment by groovytron** [comment]
From https://github.com/pypa/pipenv/issues/4058, it might be good to suggest an alternative to `pipenv` to container users.

**Comment by orsinium** [comment]
You can use [dephell](https://github.com/dephell/dephell) inside the container and read dependencies in **any** format :sparkles:

**Comment by groovytron** [comment]
Thanks fo the tip! I'll give it a try and hopefully add it to the container image if I get good results. :+1:

**Comment by groovytron** [comment]
Fixed in 41424cdc32eed6aae7bf2900fbd79aca7aab5692
